### ISSUE TITLE
Re-run stiff ODE benchmarks

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/SciMLBenchmarks.jl#128]
It's having troubles with the ODEInterface.jl binaries. @christopher-dG might need to help with getting those weird Fortran binaries to work.

**Comment by christopher-dG** [comment]
Can you link me a run where something blows up? I installed Julia + ODEInterface in a minimal container and it passes its own tests as long as gfortran is installed.

**Comment by ChrisRackauckas** [comment]
Oh sorry, this is where it was seen: https://github.com/SciML/DiffEqBenchmarks.jl/pull/118

**Comment by christopher-dG** [comment]
!rebuild StiffODE

We were missing basic build tools like `make` causing some packages to not build. I added `build-essential` which will hopefully take care of that.

**Comment by christopher-dG** [comment]
!rebuild StiffODE

I think this ought to at least mostly work now

**Comment by christopher-dG** [comment]
!rebuild StiffODE

aaaaand again, since the package renaming mucked some things up

**Comment by christopher-dG** [comment]
!rebuild StiffODE

I think I got it...

**Comment by christopher-dG** [comment]
Never mind....

**Comment by ChrisRackauckas** [comment]
close 😆

**Comment by ChrisRackauckas** [comment]
!rebuild StiffODE/VanDerPol.jmd
