### ISSUE TITLE
Re-run DynamicalODE benchmarks

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/SciMLBenchmarks.jl#131]
@SebastianM-C it looks like Weave.jl has issues with the modules. Could you update these to note use modules in the scripts?

**Comment by SebastianM-C** [comment]
Sure. I was thinking that maybe I should also calibrate the timesteps as in the nbody PR. Do you think I should do it in one PR or separate PRs?

**Comment by ChrisRackauckas** [comment]
Separate from n-body. Get it so we can merge it and run the auto-builder. There's no reason to build locally other than to check it works.

**Comment by ChrisRackauckas** [comment]
!rebuild DynamicalODE/Henon-Heiles_energy_conservation_benchmark.jmd

**Comment by ChrisRackauckas** [comment]
!rebuild DynamicalODE/Henon-Heiles_energy_conservation_benchmark.jmd

**Comment by ChrisRackauckas** [comment]
!rebuild DynamicalODE/Henon-Heiles_energy_conservation_benchmark.jmd

**Comment by ChrisRackauckas** [comment]
For sake of ease, could we just have the TaylorIntegration.jl tests just use a first order form?

**Comment by SebastianM-C** [comment]
Sure. I will special case it.

**Comment by SebastianM-C** [comment]
See #157

**Comment by ChrisRackauckas** [comment]
!rebuild DynamicalODE/Henon-Heiles_energy_conservation_benchmark.jmd
