### ISSUE TITLE
Missing BCR (1122) benchmark page

### ISSUE THREAD

**Issue by imciner2** [SciML/SciMLBenchmarks.jl#185]
The page describing the BCR (1122) stiff ODE benchmark at https://benchmarks.sciml.ai/html/Bio/BCR.html is missing and returns a 404 error.

**Comment by ChrisRackauckas** [comment]
Yeah it needs to be rebuilt.

@christopher-dG did you ever get around to changing the build action to BuildKite?

**Comment by ChrisRackauckas** [comment]
We got our benchmarking bots fixed up, and it ran fine.

https://github.com/SciML/SciMLBenchmarks.jl/pull/228

But for some reason the artifact didn't upload. @staticfloat
