### ISSUE TITLE
Finishing up the new benchmarking suite

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/SciMLBenchmarks.jl#203]
https://buildkite.com/julialang/scimlbenchmarks-dot-jl/builds/44#e548f23b-fe9b-423f-a56e-6d119291c3bd

- This only ran `linear_wpd.jmd`, so I'm a bit confused why there's so many artifacts?
- Where is it writing the artifacts to?
- The bottom of the benchmarks has `ERROR: ArgumentError: Package SciMLBenchmarks not found in current path:
- Run `import Pkg; Pkg.add("SciMLBenchmarks")` to install the SciMLBenchmarks package.`: do we need to add that to every Project.toml or can we add it globally?
- It seems like it only triggers on changes to the .jmd, and not the Project.toml. Does that mean it won't trigger on updates to the Manifest.toml either yet?

**Comment by ChrisRackauckas** [comment]
@ven-k and @staticfloat

**Comment by ven-k** [comment]
- Uploading only the changed artifacts didn't preserve the `folder/file` name. So all the artifacts are uploaded.
- It watches only .jmd files for modifications to launch the benchmark pipe (If any new package is added to `Project.toml` then that would have been used somewhere in a .jmd file so eventually launching a benchmark pipe)
-  Any changes in .toml files would result in an overall package test (ie `test/runtest.jl` is run)
- Manifest.toml is a gitignored file. (`Pkg.update()` generates/modifies this particular file. So currently I've set to not commit it in the `update.jl` file (aka via Github bot) as that would run all benchmarks, all the time. 
Maybe we could start having Manifest.toml in each directory)

**Comment by ChrisRackauckas** [comment]
>Uploading only the changed artifacts didn't preserve the folder/file name. So all the artifacts are uploaded.

No artifacts are uploaded though? It looks like they are all only in the jobs?

>It watches only .jmd files for modifications to launch the benchmark pipe (If any new package is added to Project.toml then that would have been used somewhere in a .jmd file so eventually launching a benchmark pipe)

Doesn't that conflict with how the `]up` action would trigger jobs?

**Comment by ChrisRackauckas** [comment]
For reference, the artifacts not being uploaded and only generating the .html means that we need to do things like save the html to a zip folder to reference it.

https://github.com/SciML/OrdinaryDiffEq.jl/issues/1385

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/SciMLBenchmarks.jl/pull/209 should be a big test.

**Comment by ChrisRackauckas** [comment]
@ven-k https://buildkite.com/julialang/scimlbenchmarks-dot-jl/builds/59#38f5224f-66ea-4cbe-b4a6-d8b50dcc3443 updating the Project.toml and the Manifest.toml did not start the jobs in that folder.

**Comment by ven-k** [comment]
I missed to stage `pipeline.yml` in the #208 PR. My bad.
#210 adds it now.

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/SciMLBenchmarks.jl/pull/212 didn't trigger the pipeline

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/SciMLBenchmarks.jl/commit/7e69f44acf0e32e98aeb3ddcdb1810febe41ffcb didn't trigger a job too.
