### ISSUE TITLE
Fix DynamicalODE Benchmarks

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/SciMLBenchmarks.jl#261]
Continuation of https://github.com/SciML/SciMLBenchmarks.jl/pull/229

@SebastianM-C

**Comment by SebastianM-C** [comment]
I was wondering if I should remove the iip vs oop comparison in the benchmark and just focus on comparing the solvers in the oop case.
Moreover, do you think I should other comparisons besides the one with the evolution of the energy error?
The run times and number of steps are compared in text, but there are no plots.
