### ISSUE TITLE
Fix Jumps Benchmarks

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/SciMLBenchmarks.jl#262]
Continuation of https://github.com/SciML/SciMLBenchmarks.jl/pull/230

@isaacsas

**Comment by isaacsas** [comment]
What’s wrong with them currently?

**Comment by ChrisRackauckas** [comment]
![Capture](https://user-images.githubusercontent.com/1814174/118359358-02ddc980-b551-11eb-8a9b-24de947cefee.PNG)

**Comment by ChrisRackauckas** [comment]
I'll take a stab at updating them in a few minutes. There's a few old package things that need to be updated.

**Comment by ChrisRackauckas** [comment]
First things first, they gotta get updated to Catalyst.jl, so they are pretty far behind 😅 . 

https://github.com/SciML/SciMLBenchmarks.jl/pull/275

**Comment by isaacsas** [comment]
Oh wow, that’s old. Sorry, I thought I’d updated that at some point…

**Comment by isaacsas** [comment]
I must have mixed it up with the problem library…

**Comment by ChrisRackauckas** [comment]
@Gregliest fixed two of them in https://github.com/SciML/SciMLBenchmarks.jl/pull/286 . Mendes and Diffusion are left.

Diffusion needs to be updated to use the new programmatic interface of https://catalyst.sciml.ai/dev/tutorials/generating_reactions_programmatically/ . The current version uses `rn = @empty_reaction_network` which has been entirely replaced by programmatically writing `ReactionSystem`s, which is documented there. 

I'm not sure what the other one boils down to right now.

**Comment by isaacsas** [comment]
FWIW, I think the diffusion one is very similar to what is in the problem library (which should be updated to Catalyst):

https://github.com/SciML/DiffEqProblemLibrary.jl/blob/29606924fadb5c0576e5bb87ca4c345cc1501a38/src/jump_premade_problems.jl#L237-L254
