### ISSUE TITLE
Documentation for getting started

### ISSUE THREAD

**Issue by Gregliest** [SciML/SciMLBenchmarks.jl#285]
I ran into a few issues trying to follow the instructions for getting the benchmarks up and running locally. I'm sure I'm missing some steps. I'll update the documentation, but I want to make sure that I understand the workflow before I do so. 

Here are the issues I've run into: 
1. In [Interactive Notebooks](https://github.com/SciML/SciMLBenchmarks.jl#interactive-notebooks), `SciMLBenchmarks.open_notebooks()` fails because the `notebook` folder does not exist. I'm assuming you have to run weave on one of the example to populate this folder before running `open_notebooks()`
2. In [Contributing](https://github.com/SciML/SciMLBenchmarks.jl#contributing), running `SciMLBenchmarks.weave_folder("NonStiffODE")` fails with `IOError: readdir("NonStiffODE"): no such file or directory (ENOENT)`. Looks like it needs the full path: `SciMLBenchmarks.weave_folder("benchmarks/NonStiffODE")` works.
3. Now that the `notebook` folder is populated, when running a notebook, it appears that the dependencies aren't being resolved properly. It seems that the notebooks are using the global environment, instead of the Project file for the folder. I'm not familiar enough with Julia's Pkg system to know how this is supposed to work. For instance, in `notebooks/Jumps/Mendes_multistate_example.ipynb`, the first cell fails with `ArgumentError: Package DiffEqBase not found in current path` for me. 

So, how is the workflow supposed to go? Something like the following?
1. Load SciMLBenchmarks
2. Run weave
3. Run open_notebooks() 
4. Open a notebook and run it in Jupyter (How do we resolve the package issue?)

**Comment by ChrisRackauckas** [comment]
>In Contributing, running SciMLBenchmarks.weave_folder("NonStiffODE") fails with IOError: readdir("NonStiffODE"): no such file or directory (ENOENT). Looks like it needs the full path: SciMLBenchmarks.weave_folder("benchmarks/NonStiffODE") works.

I think that's going to be dependent on the path you're running it from?

>In Interactive Notebooks, SciMLBenchmarks.open_notebooks() fails because the notebook folder does not exist. I'm assuming you have to run weave on one of the example to populate this folder before running open_notebooks()

Ahh... we recently moved the outputs to https://github.com/SciML/SciMLBenchmarksOutput , which would break this because the notebooks are no longer here 🤔 . Yeah, that's a problem.

>It seems that the notebooks are using the global environment, instead of the Project file for the folder.

You need to `]activate path/to/manifest`. We should document or make that easier.

For information on manifests and project.tomls, see https://youtu.be/QVmU29rCjaA

**Comment by Gregliest** [comment]
Ok, I think I have a better idea of what's happening now. The main sticking point is that the interactive outputs (notebooks, scripts) in https://github.com/SciML/SciMLBenchmarksOutput are going to require the manifest information in this repo to function. I see a couple main options:
1. Copy the manifest and project files from SciMLBenchmarks.jl to SciMLBenchmarksOutput. This should be easy but I don't love the duplication and the need to keep things synced betwen the two repos. There also might be issues with things like the `WEAVE_ARGS` in the script files.
2. Keep only the static outputs(html, md, and pdf) in SciMLBenchmarksOutput, and put the interactive ones in SciMLBenchmarks.jl. In this case, I think it would make sense to keep the outputs next to the source files. Then you can have a workflow like (for Jumps):
```
cd benchmarks/Jumps
]activate .
using IJulia
notebook(dir=pwd() * "/notebook/")
```

If this warrants more discussion or might be an involved project, I can update the documentation on both repos to reflect the current situation in the mean time. It looks like the SciMLBenchmarksOutput docs were copied from SciMLBenchmarks.jl and don't entirely apply. 

@ChrisRackauckas Thoughts or other ideas?

**Comment by ChrisRackauckas** [comment]
Yeah, you've identified something I didn't realize either: the manifests aren't there. 

>Copy the manifest and project files from SciMLBenchmarks.jl to SciMLBenchmarksOutput. This should be easy but I don't love the duplication and the need to keep things synced betwen the two repos. There also might be issues with things like the WEAVE_ARGS in the script files.

That sync is automatically done via bots for the web deployment anyways, so we could just make it send over the project/manifests in a nice way too. "I can update the documentation on both repos to reflect the current situation in the mean time.": update one and the bots gotcha.

Maybe @staticfloat has an idea. I might just... drop the notebook interface for now?

**Comment by Gregliest** [comment]
Cool, yeah if the sync can be set up automatically and the outputs are kept strictly downstream (which they should be I think), that sync shouldn't be a problem. If we drop the notebook interface, how do people benchmark their own machine? Via the script interface, or weave? 

I'll update the docs, hopefully by tomorrow morning. Working on the other PR right now.

**Comment by ChrisRackauckas** [comment]
I think there's instructions now so this is closed.
