### ISSUE TITLE
Fix VanDerPol and ROBER notebooks

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/SciMLBenchmarks.jl#325]
https://benchmarks.sciml.ai/html/StiffODE/VanDerPol.html
https://benchmarks.sciml.ai/html/StiffODE/ROBER.html

There are some divergent methods in there. We need to figure out what to fix up those plots.

**Comment by JunpengGao233** [comment]
Hi, It seems that in VanDerPol Problem, the QNDF diverges and in ROBER Problem, it's Rodas5.

Here is the ROBER benchmark after comment the Rodas5 in the two plots:
![rober](https://user-images.githubusercontent.com/25094000/143459971-466da1e2-3cf1-4f4b-8119-2196a70b24ee.png)
![timeseries errors](https://user-images.githubusercontent.com/25094000/143460444-a7278301-3f75-4f0d-b336-8733829f163a.png)

And Here is the VanDerPol problem benchmark after removing QNDF:
![VanDerPol](https://user-images.githubusercontent.com/25094000/143459975-fd4016e8-4896-46fd-ab0f-ddf473345a48.png)
