### ISSUE TITLE
Dynamical ODE benchmark HTML is too big

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/SciMLBenchmarks.jl#455]
https://buildkite.com/julialang/scimlbenchmarks-dot-jl/builds/811#01824571-4898-4dab-85ce-48afb9de9414/248-307

@SebastianM-C would you happen to know why it's so big? 😅

**Comment by SebastianM-C** [comment]
Yeah, there is was issue with interpolating high order solvers because the interpolating polynomial was 3rd order and would give bad energy conservation. So can't use saveats and we have a lot of points

**Comment by ChrisRackauckas** [comment]
I don't see why it would necessarily lead to a large HTML though. Is it plotting a bunch of points?

**Comment by SebastianM-C** [comment]
Yeah, Plots doesn't subsample/rasterize the input. I think that https://github.com/SciML/OrdinaryDiffEq.jl/issues/421 is the related issue.

**Comment by ChrisRackauckas** [comment]
No more HTMLs
