### ISSUE TITLE
Jump process benchmarks are old

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/SciMLBenchmarks.jl#456]
They are back in DiffEqJump land, and pretty old for that as well.

@isaacsas 

```julia
Benchmarking method: DiffEqJump.Direct()
Error: UndefVarError: JumpProblem not defined
```

https://benchmarks.sciml.ai/dev/Jumps/Diffusion_CTRW/

Seems easy to fix, maybe one of us can catch it in the next week.

**Comment by isaacsas** [comment]
We need to pet over some of @TorkelE’s examples too.

**Comment by isaacsas** [comment]
Port over. Nice autocorrect there…

**Comment by ChrisRackauckas** [comment]
Agreed, and we should do it before they go stale 😅

**Comment by isaacsas** [comment]
Handled in https://github.com/SciML/SciMLBenchmarks.jl/pull/408
