### ISSUE TITLE
Errors in SciMLBenchmarks.jl

### ISSUE THREAD

**Issue by iajzenszmi** [SciML/SciMLBenchmarks.jl#457]
ian@ian-HP-Stream-Laptop-11-y0XX:~$ cd julia* 
bash: cd: too many arguments
ian@ian-HP-Stream-Laptop-11-y0XX:~$ cd julia*
bash: cd: too many arguments
ian@ian-HP-Stream-Laptop-11-y0XX:~$ cd Downloads
ian@ian-HP-Stream-Laptop-11-y0XX:~/Downloads$ ls julia*
julia-1.6.6-linux-x86_64.tar.gz  julia-1.7.3-linux-x86_64.tar.gz
ian@ian-HP-Stream-Laptop-11-y0XX:~/Downloads$ cd
ian@ian-HP-Stream-Laptop-11-y0XX:~$ ls julia*
julia-1.7.3-linux-x86_64.tar.gz

julia-1.7.3:
bin  etc  include  lib  libexec  LICENSE.md  share
ian@ian-HP-Stream-Laptop-11-y0XX:~$ cd julia-1.7.3:
bash: cd: julia-1.7.3:: No such file or directory
ian@ian-HP-Stream-Laptop-11-y0XX:~$ cd Downloads
ian@ian-HP-Stream-Laptop-11-y0XX:~/Downloads$ cd julia-1.7.3
bash: cd: julia-1.7.3: No such file or directory
ian@ian-HP-Stream-Laptop-11-y0XX:~/Downloads$ cd

(@v1.7) pkg> add benchmarks
    Updating registry at `~/.julia/registries/General.toml`
ERROR: The following package names could not be resolved:
 * benchmarks (not found in project, manifest or registry)

(@v1.7) pkg> add SciMLBenchmarks.jl
   Resolving package versions...
   Installed libsodium_jll ─── v1.0.20+0
   Installed ZeroMQ_jll ────── v4.3.4+0
   Installed SoftGlobalScope ─ v1.1.0
   Installed Git_jll ───────── v2.34.1+0
   Installed IJulia ────────── v1.23.3
   Installed Highlights ────── v0.4.5
   Installed Weave ─────────── v0.10.9
   Installed SciMLBenchmarks ─ v0.1.0
   Installed Git ───────────── v1.2.1
   Installed ZMQ ───────────── v1.2.1
  Downloaded artifact: Git
  Downloaded artifact: libsodium
  Downloaded artifact: ZeroMQ
    Updating `~/.julia/environments/v1.7/Project.toml`
  [31c91b34] + SciMLBenchmarks v0.1.0
    Updating `~/.julia/environments/v1.7/Manifest.toml`
  [8f4d0f93] + Conda v1.7.0
  [d7ba0133] + Git v1.2.1
  [eafb193a] + Highlights v0.4.5
  [7073ff75] + IJulia v1.23.3
  [ffc61752] + Mustache v1.0.14
  [31c91b34] + SciMLBenchmarks v0.1.0
  [b85f4697] + SoftGlobalScope v1.1.0
  [81def892] + VersionParsing v1.3.0
  [44d3d7a6] + Weave v0.10.9
  [c2297ded] + ZMQ v1.2.1
  [f8c6e375] + Git_jll v2.34.1+0
  [8f1865be] + ZeroMQ_jll v4.3.4+0
  [a9144af2] + libsodium_jll v1.0.20+0
  [efcefdf7] + PCRE2_jll
    Building IJulia → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/98ab633acb0fe071b671f6c1785c46cd70bb86bd/build.log`
Precompiling project...
  12 dependencies successfully precompiled in 37 seconds (437 already precompiled, 1 skipped during auto due to previous errors)

(@v1.7) pkg> test SciMLBenchmarks.jl
     Testing SciMLBenchmarks
      Status `/tmp/jl_HuvIAV/Project.toml`
  [d7ba0133] Git v1.2.1
  [7073ff75] IJulia v1.23.3
  [91a5bcdd] Plots v1.31.3
  [31c91b34] SciMLBenchmarks v0.1.0
  [44d3d7a6] Weave v0.10.9
  [b77e0a4c] InteractiveUtils `@stdlib/InteractiveUtils`
  [d6f4376e] Markdown `@stdlib/Markdown`
  [44cfe95a] Pkg `@stdlib/Pkg`
  [8dfed614] Test `@stdlib/Test`
      Status `/tmp/jl_HuvIAV/Manifest.toml`
  [79e6a3ab] Adapt v3.3.3
  [d360d2e6] ChainRulesCore v1.15.0
  [9e997f8a] ChangesOfVariables v0.1.3
  [944b1d66] CodecZlib v0.7.0
  [35d6a980] ColorSchemes v3.19.0
  [3da002f7] ColorTypes v0.11.4
  [c3611d14] ColorVectorSpace v0.9.9
  [5ae59095] Colors v0.12.8
  [34da2185] Compat v3.45.0
  [8f4d0f93] Conda v1.7.0
  [d38c429a] Contour v0.6.2
  [9a962f9c] DataAPI v1.10.0
  [864edb3b] DataStructures v0.18.13
  [e2d170a0] DataValueInterfaces v1.0.0
  [ffbed154] DocStringExtensions v0.8.6
  [c87230d0] FFMPEG v0.4.1
  [53c48c17] FixedPointNumbers v0.8.4
  [59287772] Formatting v0.4.2
  [28b8d3ca] GR v0.66.0
  [5c1252a2] GeometryBasics v0.4.2
  [d7ba0133] Git v1.2.1
  [42e2da0e] Grisu v1.0.2
  [cd3eb016] HTTP v1.2.0
  [eafb193a] Highlights v0.4.5
  [7073ff75] IJulia v1.23.3
  [83e8ac13] IniFile v0.5.1
  [3587e190] InverseFunctions v0.1.7
  [92d709cd] IrrationalConstants v0.1.1
  [c8e1da08] IterTools v1.4.0
  [82899510] IteratorInterfaceExtensions v1.0.0
  [692b3bcd] JLLWrappers v1.4.1
  [682c06a0] JSON v0.21.3
  [b964fa9f] LaTeXStrings v1.3.0
  [23fbe1c1] Latexify v0.15.15
  [2ab3a3ac] LogExpFunctions v0.3.15
  [e6f89c97] LoggingExtras v0.4.9
  [1914dd2f] MacroTools v0.5.9
  [739be429] MbedTLS v1.1.1
  [442fdcdd] Measures v0.3.1
  [e1d29d7a] Missings v1.0.2
  [ffc61752] Mustache v1.0.14
  [77ba4419] NaNMath v0.3.7
  [bac558e1] OrderedCollections v1.4.1
  [69de0a69] Parsers v2.3.2
  [ccf2f8ad] PlotThemes v3.0.0
  [995b91a9] PlotUtils v1.3.0
  [91a5bcdd] Plots v1.31.3
  [21216c6a] Preferences v1.3.0
  [3cdcf5f2] RecipesBase v1.2.1
  [01d81517] RecipesPipeline v0.6.2
  [189a3867] Reexport v1.2.2
  [05181044] RelocatableFolders v0.3.0
  [ae029012] Requires v1.3.0
  [31c91b34] SciMLBenchmarks v0.1.0
  [6c6a2e73] Scratch v1.1.1
  [992d4aef] Showoff v1.0.3
  [777ac1f9] SimpleBufferStream v1.1.0
  [b85f4697] SoftGlobalScope v1.1.0
  [a2af1166] SortingAlgorithms v1.0.1
  [276daf66] SpecialFunctions v2.1.6
  [90137ffa] StaticArrays v1.4.7
  [82ae8749] StatsAPI v1.4.0
  [2913bbd2] StatsBase v0.33.17
  [69024149] StringEncodings v0.3.5
  [09ab397b] StructArrays v0.6.10
  [3783bdb8] TableTraits v1.0.1
  [bd369af6] Tables v1.7.0
  [62fd8b95] TensorCore v0.1.1
  [3bb67fe8] TranscodingStreams v0.9.6
  [5c2747f8] URIs v1.3.0
  [1cfade01] UnicodeFun v0.4.1
  [41fe7b60] Unzip v0.1.2
  [81def892] VersionParsing v1.3.0
  [44d3d7a6] Weave v0.10.9
  [ddb6d928] YAML v0.4.7
  [c2297ded] ZMQ v1.2.1
  [6e34b625] Bzip2_jll v1.0.8+0
  [83423d85] Cairo_jll v1.16.1+1
  [5ae413db] EarCut_jll v2.2.3+0
  [2e619515] Expat_jll v2.4.8+0
  [b22a6f82] FFMPEG_jll v4.4.2+0
  [a3f928ae] Fontconfig_jll v2.13.93+0
  [d7e528f0] FreeType2_jll v2.10.4+0
  [559328eb] FriBidi_jll v1.0.10+0
  [0656b61e] GLFW_jll v3.3.6+0
  [d2c73de3] GR_jll v0.66.0+0
  [78b55507] Gettext_jll v0.21.0+0
  [f8c6e375] Git_jll v2.34.1+0
  [7746bdde] Glib_jll v2.68.3+2
  [3b182d85] Graphite2_jll v1.3.14+0
  [2e76f6c2] HarfBuzz_jll v2.8.1+1
  [aacddb02] JpegTurbo_jll v2.1.2+0
  [c1c5ebd0] LAME_jll v3.100.1+0
  [88015f11] LERC_jll v3.0.0+1
  [dd4b983a] LZO_jll v2.10.1+0
  [e9f186c6] Libffi_jll v3.2.2+1
  [d4300ac3] Libgcrypt_jll v1.8.7+0
  [7e76a0d4] Libglvnd_jll v1.3.0+3
  [7add5ba3] Libgpg_error_jll v1.42.0+0
  [94ce4f54] Libiconv_jll v1.16.1+1
  [4b2f31a3] Libmount_jll v2.35.0+0
  [89763e89] Libtiff_jll v4.4.0+0
  [38a345b3] Libuuid_jll v2.36.0+0
  [e7412a2a] Ogg_jll v1.3.5+1
  [458c3c95] OpenSSL_jll v1.1.17+0
  [efe28fd5] OpenSpecFun_jll v0.5.5+0
  [91d4177d] Opus_jll v1.3.2+0
  [2f80f16e] PCRE_jll v8.44.0+0
  [30392449] Pixman_jll v0.40.1+0
  [ea2cea3b] Qt5Base_jll v5.15.3+1
  [a2964d1f] Wayland_jll v1.19.0+0
  [2381bf8a] Wayland_protocols_jll v1.25.0+0
  [02c8fc9c] XML2_jll v2.9.14+0
  [aed1982a] XSLT_jll v1.1.34+0
  [4f6342f7] Xorg_libX11_jll v1.6.9+4
  [0c0b7dd1] Xorg_libXau_jll v1.0.9+4
  [935fb764] Xorg_libXcursor_jll v1.2.0+4
  [a3789734] Xorg_libXdmcp_jll v1.1.3+4
  [1082639a] Xorg_libXext_jll v1.3.4+4
  [d091e8ba] Xorg_libXfixes_jll v5.0.3+4
  [a51aa0fd] Xorg_libXi_jll v1.7.10+4
  [d1454406] Xorg_libXinerama_jll v1.1.4+4
  [ec84b674] Xorg_libXrandr_jll v1.5.2+4
  [ea2f1a96] Xorg_libXrender_jll v0.9.10+4
  [14d82f49] Xorg_libpthread_stubs_jll v0.1.0+3
  [c7cfdc94] Xorg_libxcb_jll v1.13.0+3
  [cc61e674] Xorg_libxkbfile_jll v1.1.0+4
  [12413925] Xorg_xcb_util_image_jll v0.4.0+1
  [2def613f] Xorg_xcb_util_jll v0.4.0+1
  [975044d2] Xorg_xcb_util_keysyms_jll v0.4.0+1
  [0d47668e] Xorg_xcb_util_renderutil_jll v0.3.9+1
  [c22f9ab0] Xorg_xcb_util_wm_jll v0.4.1+1
  [35661453] Xorg_xkbcomp_jll v1.4.2+4
  [33bec58e] Xorg_xkeyboard_config_jll v2.27.0+4
  [c5fb5394] Xorg_xtrans_jll v1.4.0+3
  [8f1865be] ZeroMQ_jll v4.3.4+0
  [3161d3a3] Zstd_jll v1.5.2+0
  [a4ae2306] libaom_jll v3.4.0+0
  [0ac62f75] libass_jll v0.15.1+0
  [f638f0a6] libfdk_aac_jll v2.0.2+0
  [b53b4c65] libpng_jll v1.6.38+0
  [a9144af2] libsodium_jll v1.0.20+0
  [f27f6e37] libvorbis_jll v1.3.7+1
  [1270edf5] x264_jll v2021.5.5+0
  [dfaa095f] x265_jll v3.5.0+0
  [d8fb68d0] xkbcommon_jll v0.9.1+5
  [0dad84c5] ArgTools `@stdlib/ArgTools`
  [56f22d72] Artifacts `@stdlib/Artifacts`
  [2a0f44e3] Base64 `@stdlib/Base64`
  [ade2ca70] Dates `@stdlib/Dates`
  [8bb1440f] DelimitedFiles `@stdlib/DelimitedFiles`
  [8ba89e20] Distributed `@stdlib/Distributed`
  [f43a241f] Downloads `@stdlib/Downloads`
  [7b1f6079] FileWatching `@stdlib/FileWatching`
  [b77e0a4c] InteractiveUtils `@stdlib/InteractiveUtils`
  [b27032c2] LibCURL `@stdlib/LibCURL`
  [76f85450] LibGit2 `@stdlib/LibGit2`
  [8f399da3] Libdl `@stdlib/Libdl`
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`
  [56ddb016] Logging `@stdlib/Logging`
  [d6f4376e] Markdown `@stdlib/Markdown`
  [a63ad114] Mmap `@stdlib/Mmap`
  [ca575930] NetworkOptions `@stdlib/NetworkOptions`
  [44cfe95a] Pkg `@stdlib/Pkg`
  [de0858da] Printf `@stdlib/Printf`
  [3fa0cd96] REPL `@stdlib/REPL`
  [9a3f8284] Random `@stdlib/Random`
  [ea8e919c] SHA `@stdlib/SHA`
  [9e88b42a] Serialization `@stdlib/Serialization`
  [1a1011a3] SharedArrays `@stdlib/SharedArrays`
  [6462fe0b] Sockets `@stdlib/Sockets`
  [2f01184e] SparseArrays `@stdlib/SparseArrays`
  [10745b16] Statistics `@stdlib/Statistics`
  [fa267f1f] TOML `@stdlib/TOML`
  [a4e569a6] Tar `@stdlib/Tar`
  [8dfed614] Test `@stdlib/Test`
  [cf7118a7] UUIDs `@stdlib/UUIDs`
  [4ec0a83e] Unicode `@stdlib/Unicode`
  Downloaded artifact: Libtiff
  Downloaded artifact: LAME
  Downloaded artifact: PCRE
  Downloaded artifact: Libiconv
  Downloaded artifact: Libffi
  Downloaded artifact: LZO
  Downloaded artifact: libvorbis
  Downloaded artifact: Glib
  Downloaded artifact: FriBidi
  Downloaded artifact: Ogg
  Downloaded artifact: XSLT
  Downloaded artifact: Cairo
  Downloaded artifact: ZeroMQ
  Downloaded artifact: Fontconfig
  Downloaded artifact: GLFW
  Downloaded artifact: Libgpg_error
  Downloaded artifact: x264
  Downloaded artifact: FreeType2
  Downloaded artifact: Libuuid
  Downloaded artifact: libpng
    Building Conda ─→ `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/299304989a5e6473d985212c28928899c74e9421/build.log`
    Building IJulia → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/d8b9c31196e1dd92181cd0f5760ca2d2ffb4ac0f/build.log`
    Building GR ────→ `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/011458b83178ac913dc4eb73b229af45bdde5d83/build.log`
  ✓ Requires
  ✓ DataAPI
  ✓ YAML
  ✓ Preferences
  ✓ Highlights
  ✓ Tables
  ✓ JLLWrappers
  ✓ Mustache
  ✓ Libiconv_jll
  ✓ libsodium_jll
  ✓ Weave
  ✓ ZeroMQ_jll
  ✓ ZMQ
  ✓ IJulia
  ✓ SciMLBenchmarks
  111 dependencies successfully precompiled in 390 seconds (20 already precompiled)
  17 dependencies precompiled but different versions are currently loaded. Restart julia to access the new versions
    Building Conda ─→ `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/299304989a5e6473d985212c28928899c74e9421/build.log`
    Building IJulia → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/d8b9c31196e1dd92181cd0f5760ca2d2ffb4ac0f/build.log`
    Building GR ────→ `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/011458b83178ac913dc4eb73b229af45bdde5d83/build.log`
Building Script
[ Info: Tangled to /home/ian/.julia/packages/SciMLBenchmarks/drn2N/script/Testing/test.jl
Building HTML
┌ Info: Weaving chunk 1 from line 9
└   progress = 0.0
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
┌ Info: Weaving chunk 2 from line 26
└   progress = 0.5
┌ Info: Weaved all chunks
└   progress = 1
[ Info: Weaved to /home/ian/.julia/packages/SciMLBenchmarks/drn2N/html/Testing/test.html
Building PDF
┌ Info: Weaving chunk 1 from line 9
└   progress = 0.0
┌ Info: Weaving chunk 2 from line 26
└   progress = 0.5
┌ Info: Weaved all chunks
└   progress = 1
┌ Warning: Error converting document to pdf. Try running latex manually
└ @ Weave ~/.julia/packages/Weave/ijcKV/src/writer/latex.jl:12
┌ Warning: PDF generation failed
│   exception =
│    IOError: could not spawn `xelatex -shell-escape -halt-on-error test.tex`: no such file or directory (ENOENT)
│    Stacktrace:
│      [1] _spawn_primitive(file::String, cmd::Cmd, stdio::Vector{Any})
│        @ Base ./process.jl:100
│      [2] #693
│        @ ./process.jl:113 [inlined]
│      [3] setup_stdios(f::Base.var"#693#694"{Cmd}, stdios::Vector{Any})
│        @ Base ./process.jl:197
│      [4] _spawn
│        @ ./process.jl:112 [inlined]
│      [5] run(::Cmd; wait::Bool)
│        @ Base ./process.jl:454
│      [6] run
│        @ ./process.jl:453 [inlined]
│      [7] write_doc(docformat::Weave.LaTeX2PDF, doc::Weave.WeaveDoc, rendered::String, out_path::String)
│        @ Weave ~/.julia/packages/Weave/ijcKV/src/writer/latex.jl:10
│      [8] write_doc(doc::Weave.WeaveDoc, rendered::String, out_path::String)
│        @ Weave ~/.julia/packages/Weave/ijcKV/src/writer/writer.jl:2
│      [9] weave(source::String; doctype::String, informat::Nothing, out_path::String, args::Dict{Symbol, String}, mod::Nothing, fig_path::Nothing, fig_ext::Nothing, cache_path::String, cache::Symbol, template::Nothing, css::Nothing, highlight_theme::Nothing, pandoc_options::Vector{String}, latex_cmd::Vector{String}, keep_unicode::Bool)
│        @ Weave ~/.julia/packages/Weave/ijcKV/src/Weave.jl:227
│     [10] weave_file(folder::String, file::String, build_list::NTuple{5, Symbol})
│        @ SciMLBenchmarks ~/.julia/packages/SciMLBenchmarks/drn2N/src/SciMLBenchmarks.jl:36
│     [11] weave_file(folder::String, file::String)
│        @ SciMLBenchmarks ~/.julia/packages/SciMLBenchmarks/drn2N/src/SciMLBenchmarks.jl:8
│     [12] macro expansion
│        @ ~/.julia/packages/SciMLBenchmarks/drn2N/test/runtests.jl:5 [inlined]
│     [13] macro expansion
│        @ ~/julia-1.7.3/share/julia/stdlib/v1.7/Test/src/Test.jl:1283 [inlined]
│     [14] top-level scope
│        @ ~/.julia/packages/SciMLBenchmarks/drn2N/test/runtests.jl:4
│     [15] include(fname::String)
│        @ Base.MainInclude ./client.jl:451
│     [16] top-level scope
│        @ none:6
│     [17] eval
│        @ ./boot.jl:373 [inlined]
│     [18] exec_options(opts::Base.JLOptions)
│        @ Base ./client.jl:268
│     [19] _start()
│        @ Base ./client.jl:495
└ @ SciMLBenchmarks ~/.julia/packages/SciMLBenchmarks/drn2N/src/SciMLBenchmarks.jl:38
Building Github Markdown
┌ Info: Weaving chunk 1 from line 9
└   progress = 0.0
┌ Info: Weaving chunk 2 from line 26
└   progress = 0.5
┌ Info: Weaved all chunks
└   progress = 1
[ Info: Weaved to /home/ian/.julia/packages/SciMLBenchmarks/drn2N/markdown/Testing/test.md
Building Notebook
weave_file: Test Failed at /home/ian/.julia/packages/SciMLBenchmarks/drn2N/test/runtests.jl:10
  Expression: isfile(joinpath(dirname(#= /home/ian/.julia/packages/SciMLBenchmarks/drn2N/test/runtests.jl:10 =# @__DIR__()), "pdf", "Testing", "test.pdf"))
Stacktrace:
 [1] macro expansion
   @ ~/julia-1.7.3/share/julia/stdlib/v1.7/Test/src/Test.jl:445 [inlined]
 [2] macro expansion
   @ ~/.julia/packages/SciMLBenchmarks/drn2N/test/runtests.jl:10 [inlined]
 [3] macro expansion
   @ ~/julia-1.7.3/share/julia/stdlib/v1.7/Test/src/Test.jl:1283 [inlined]
 [4] top-level scope
   @ ~/.julia/packages/SciMLBenchmarks/drn2N/test/runtests.jl:4
Test Summary: | Pass  Fail  Total
weave_file    |    3     1      4
ERROR: LoadError: Some tests did not pass: 3 passed, 1 failed, 0 errored, 0 broken.
in expression starting at /home/ian/.julia/packages/SciMLBenchmarks/drn2N/test/runtests.jl:3
ERROR: Package SciMLBenchmarks errored during testing

**Comment by ChrisRackauckas** [comment]
Are you running this in a fresh project? No global packages?

**Comment by iajzenszmi** [comment]
I have run this with the julia command, then the "]", then "add SciMLBenchmarks" then "test SciMLBenchmarks" .

**Comment by ChrisRackauckas** [comment]
You have to dev it. The released version is old.

**Comment by ChrisRackauckas** [comment]
New release is now v0.1.1. Just update and you should be good. That said, if you're not deving this library, then I don't know what you're doing with the tests.
