### ISSUE TITLE
Fixing the Stan binary for the Bayesian estimation

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/SciMLBenchmarks.jl#484]
The Stan integration for Bayesian estimation broke. The latest one that worked was v1.4.

https://benchmarks.sciml.ai/stable/ParameterEstimation/DiffEqBayesFitzHughNagumo/
https://benchmarks.sciml.ai/stable/ParameterEstimation/DiffEqBayesLotkaVolterra/

The latest attempt was in https://github.com/SciML/SciMLBenchmarks.jl/pull/362 . If you check the artifacts of the latest build (https://buildkite.com/julialang/scimlbenchmarks-dot-jl/builds/904#0182b81c-d678-4f82-aaf3-e1a49cf5b0b5), you see:

```
Error: IOError: cd(""): no such file or directory (ENOENT)
```

for the call `@btime bayesian_result_stan = stan_inference(prob_ode_fitzhughnagumo,t,data,priors; print_summary=false, vars=(DiffEqBayes.StanODEData(), InverseGamma(2, 3)))`. @Vaibhavdixit02 tried to get the Stan installation to be automatic, but it seems to be pretty hard.

Pinging all who were involved there: @Vaibhavdixit02 , @ven-k , @goedman, @staticfloat. And @mohamed82008 + @storopoli

**Comment by ChrisRackauckas** [comment]
On-going developments are setup to occur in https://github.com/SciML/SciMLBenchmarks.jl/pull/485.

**Comment by storopoli** [comment]
I think that 6 months ago, the Stan devs managed to get an anaconda packaged up for CmdStan and also they are commmited to maintaining it: https://anaconda.org/conda-forge/cmdstan

@Vaibhavdixit02, that could be a good alternative. What do you think?

**Comment by storopoli** [comment]
Additionally, for [`StanSample.jl`](https://github.com/StanJulia/StanSample.jl), we need to export the `CMDSTAN` or `JULIA_CMDSTAN` environment variables as described in the `README.md`:

```bash
export CMDSTAN=your/absolute/path/to/cmdstan
```

```julia
ENV["CMDSTAN"]="_your absolute path to cmdstan_"
```

**Comment by storopoli** [comment]
Looking here: https://github.com/SciML/SciMLBenchmarks.jl/blob/master/.buildkite/run_benchmark.yml#L49

I think that we are exporting the wrong variable name and also the relative path instead of the "absolute path to the cmdstan".

**Comment by Vaibhavdixit02** [comment]
The name of the variable is correct, you might right about the relative path causing the error, will take a look at that

**Comment by goedman** [comment]
Hi @Vaibhavdixit02 

In your updates above, I think you're trying to set CMDSTAN_HOME directly. The ENV var needs to be CMDSTAN which is then used to define CMDSTAN_HOME. It needs to be the absolute path.

I'm struggling a bit to get/find the Github workflow output file referred to above by Chris, but I'll dig a bit deeper. Seeing the workflow output would help me confirm above suspicion.

Rob

```
julia> using StanSample

help?> ?CMDSTAN_HOME
search: CMDSTAN_HOME set_cmdstan_home!

  The directory which contains the cmdstan executables such as bin/stanc
  and bin/stansummary.

  Extended help
  ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡

  Inferred from the environment variable CMDSTAN or ENV["CMDSTAN"] when
  available.

  If these are not available, use set_cmdstan_home! to set the value of
  CMDSTAN_HOME.

  Example: set_cmdstan_home!(homedir() * "/Projects/Stan/cmdstan/")

  Executing versioninfo() will display the value of CMDSTAN if defined.

julia> CMDSTAN_HOME
"/Users/rob/Projects/StanSupport/cmdstan/"
```

**Comment by Vaibhavdixit02** [comment]
Hi Rob, thanks for looking into this, actually I was able to get stan running now with @ven-k 's help. I could use your help for this error though, getting this for the FitzHugh Nagumo equation benchmark

```
Error: 
Error when compiling SampleModel parameter_estimation_model:
Syntax error in '/tmp/jl_VoggaC/parameter_estimation_model.stan', line 5, c
olumn 2 to column 19, parsing error:
   -------------------------------------------------
     3:    vector[2] internal_var___du;
     4:    internal_var___du[1] = internal_var___p_4 + -1//3 * internal_var
___u[1] ^ 3 + -1 * internal_var___u[2] + internal_var___u[1];
     5:    internal_var___du[2] = internal_var___p_3 * (internal_var___p_1 
+ -1 * internal_var___p_2 * internal_var___u[2] + internal_var___u[1]);
           ^
     6:    return internal_var___du;
     7:  }
   -------------------------------------------------

Ill-formed expression. Found an expression. Expect an infix or postfix oper
ator or "["
make: *** [make/program:50: /tmp/jl_VoggaC/parameter_estimation_model.hpp] 
Error 1
```

**Comment by goedman** [comment]
Just ran that test before sending above email, the complete function looks like:
```
functions {
            
  vector sho(
    real t,vector internal_var___u, 
    real internal_var___p_1, real internal_var___p_2, 
    real internal_var___p_3, real internal_var___p_4) {

  vector[2] internal_var___du;

  internal_var___du[1] = internal_var___p_4 - 0.3333 * internal_var___u[1] ^ 3 + -1 * internal_var___u[2] + internal_var___u[1];
  internal_var___du[2] = internal_var___p_3 * (internal_var___p_1 + -1 * internal_var___p_2 * internal_var___u[2] + internal_var___u[1]);

  return internal_var___du;
}
```

Can you see the entire definition? Looks like something went wrong in the parameters passed in.

**Comment by goedman** [comment]
I'm a bit concerned in the expression generated here to see: "+ -1//3 * internal_var___u[1] ^ 3". The -1//3 part.

**Comment by goedman** [comment]
Vaguely I remember this issue and fixed it a year ago by using:
```
fitz = @ode_def FitzhughNagumo begin
  dv = v - v^3/3 -w + l
  dw = τinv*(v +  a - b*w)
end a b τinv l
```
