### ISSUE TITLE
Ensure Stan defaults used in benchmarks

### ISSUE THREAD

**Issue by andrewjradcliffe** [SciML/SciMLBenchmarks.jl#489]
Related to this [recent issue](https://github.com/SciML/SciMLBenchmarks.jl/issues/484#issue-1346451770).

From [this](https://discourse.julialang.org/t/improving-performance-of-item-response-model-in-turing-jl/86249/21) Discourse thread, there is clear motivation for use of the Stan defaults; this directly affects the benchmark comparisons (see the examples in #484). 

I might suggest that if the Stan defaults are not used, an explanation be given. In the [v1.4](https://benchmarks.sciml.ai/html/ParameterEstimation/DiffEqBayesFitzHughNagumo.html) benchmarks, `stepsize_jitter=1` is a poignant example where misleading conclusions may be drawn. It is important to explain such choices, particularly when said choices are discouraged by the [Stan documentation](https://mc-stan.org/docs/cmdstan-guide/mcmc-config.html#algorithm).

**Comment by ChrisRackauckas** [comment]
This repo just uses the Stan defaults. Please open an issue on the Stan repositories about the defaults if they should be different.

It's not present in DiffEqBayes.jl at all: https://github.com/SciML/DiffEqBayes.jl/search?q=stepsize_jitter

nor SciMLBenchmarks: https://github.com/SciML/SciMLBenchmarks.jl/search?q=stepsize_jitter&type=

so we don't even use that phrase anywhere.

**Comment by ChrisRackauckas** [comment]
Let's see what happens after https://github.com/SciML/SciMLBenchmarks.jl/pull/485

**Comment by goedman** [comment]
Hmm, is this (stepwise_jitter=1.0) true?

StanSample.jl (and thus Stan.jl) has at least for 2 years (but likely much longer) used below stepwise_jitter setting:
```
julia> bayesian_result_stan.model

Model name:
  name =                    parameter_estimation_model

C++ threads per forked process:
  num_threads =             8
  use_cpp_chains =          false
  check_num_chains =        true

C++ chains per forked process:
  num_cpp_chains =          1

No of forked Julia processes:
  num_julia_chains =        4

Actual number of chains:
  num_chains =              4

Sample section:
  num_samples =             1000
  num_warmups =             1000
  save_warmup =             false
  thin =                    1
  seed =                    -1
  refresh =                 100
  init_bound =              2

Adapt section:
  engaged =                 true
  gamma =                   0.05
  delta =                   0.8
  kappa =                   0.75
  t0 =                      10
  init_buffer =             75
  term_buffer =             50
  window =                  25

Algorithm section:

  algorithm =               hmc

    NUTS section:
      engine =              nuts
      max_depth =           10

  Metric section:
    metric =                diag_e
    stepsize =              1.0
    stepsize_jitter =       0.0

Data and init files:
  use_json =                true

Stansummary section:
  summary                   true
  print_summary             false

Other:
  output_base =             /Users/rob/.julia/dev/DiffEqBayesStan/examples/Fitzhugh-Nagumo/tmp/parameter_estimation_model
  tmpdir =                  /Users/rob/.julia/dev/DiffEqBayesStan/examples/Fitzhugh-Nagumo/tmp

```

which results on my machine in:
```
julia> include("/Users/rob/.julia/dev/DiffEqBayesStan/examples/Fitzhugh-Nagumo/fn.jl");
  8.037559 seconds (2.07 k allocations: 202.500 KiB)
```.

The command line looks like:
```
julia> bayesian_result_stan.model.cmds
4-element Vector{Cmd}:
 `/Users/rob/.julia/dev/DiffEqBayesStan/examples/Fitzhugh-Nagumo/tmp/parameter_estimation_model sample num_samples=1000 num_warmup=1000 save_warmup=0 thin=1 adapt engaged=1 gamma=0.05 delta=0.8 kappa=0.75 t0=10 init_buffer=75 term_buffer=75 window=25 algorithm=hmc engine=nuts max_depth=10 metric=diag_e stepsize=1.0 stepsize_jitter=0.0 random seed=-1 init=2 id=1 data file=/Users/rob/.julia/dev/DiffEqBayesStan/examples/Fitzhugh-Nagumo/tmp/parameter_estimation_model_data_1.json output file=/Users/rob/.julia/dev/DiffEqBayesStan/examples/Fitzhugh-Nagumo/tmp/parameter_estimation_model_chain_1.csv refresh=100`
```

A performance plot can be seen below (from about a year ago):
![performance_2021](https://user-images.githubusercontent.com/52200/187924350-f4bf6b99-3dc3-41a3-b40b-ff5faa0c4a16.png)

I'll rerun these timings later today.

**Comment by ChrisRackauckas** [comment]
I don't see the stepsize_jitter mentioned in the updated results: https://benchmarks.sciml.ai/dev/BayesianInference/DiffEqBayesFitzHughNagumo/ so I assume this was just an issue with an older Stan.jl
