### ISSUE TITLE
Newly added Gupta (bio) benchmarks links not working in the Readme

### ISSUE THREAD

**Issue by TorkelE** [SciML/SciMLBenchmarks.jl#498]
I recently added these benchmarks:
https://github.com/SciML/SciMLBenchmarks.jl/pull/487

However, when go to the SciML page and try to click on the benchmarks, the links do not work:https://benchmarks.sciml.ai/html/Bio/multistate.html

These are the problem benchmarks:
[Multistate (9 ODE) Work-Precision Diagram](https://benchmarks.sciml.ai/html/Bio/multistate.html)
[Multisite2 (66 ODE) Work-Precision Diagram](https://benchmarks.sciml.ai/html/Bio/multisite2.html)
[Egfr_net (356 ODE) Work-Precision Diagram](https://benchmarks.sciml.ai/html/Bio/egfr_net.html)

I have tried to figure out how the docs work, and why I cannot find these, but I haven't managed to.

**Comment by ChrisRackauckas** [comment]
The HTMLs are no longer used. It all builds the site, and I see them on there:

* https://benchmarks.sciml.ai/dev/Bio/egfr_net/
* https://benchmarks.sciml.ai/dev/Bio/multisite2/
* https://benchmarks.sciml.ai/dev/Bio/multistate/

**Comment by TorkelE** [comment]
Thanks, that's useful!
