### ISSUE TITLE
PDE notebooks need to be rerun or re-linked

### ISSUE THREAD

**Issue by Datseris** [SciML/SciMLBenchmarks.jl#53]
What I've noticed is that most (I didn't check all of them) PDE notebooks need to be rerun: all cells just display error messages.

E.g.:

http://benchmarks.juliadiffeq.org/html/MOLPDE/allen_cahn_spectral_wpd.html

http://benchmarks.juliadiffeq.org/html/MOLPDE/kdv_spectral_wpd.html

**Comment by ChrisRackauckas** [comment]
oh haha, yes ApproxFun needs to be added to the Project.toml

**Comment by ChrisRackauckas** [comment]
These are being re-run on the server right after the next run of Filament.

**Comment by ChrisRackauckas** [comment]
These are gone, now we just have the website.
