### ISSUE TITLE
Benchmarks for nonlinear solvers

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/SciMLBenchmarks.jl#570]
With @CCsimon123's advancements to NonlinearSolve.jl it's ready for benchmarking. But we need to setup some benchmarks for the nonlinear solvers. Is there a good test suite out there?

@oscardssmith do you have a case to use?

**Comment by avik-pal** [comment]
@oscardssmith was there a specific problem to benchmark here? We do have quite a few in already and have some more incoming

**Comment by oscardssmith** [comment]
I don't have a specific benchmark. I believe this was in reference to me telling @ChrisRackauckas that Nonlinearsolve.jl was slower and less stable than NLSolve before we fixed up NonlinearSolve. I think this can be closed.
