### ISSUE TITLE
Multivariate Hawkes SSA benchmark broken

### ISSUE THREAD

**Issue by Vilin97** [SciML/SciMLBenchmarks.jl#825]
The [Multivariate Hawkes benchmark](https://docs.sciml.ai/SciMLBenchmarksOutput/stable/Jumps/MultivariateHawkes/) is broken.

**Comment by Vilin97** [comment]
The [gene expression benchmark](https://docs.sciml.ai/SciMLBenchmarksOutput/stable/Jumps/NegFeedback_GeneExpr_Marchetti/) is also broken.

**Comment by Spinachboul** [comment]
What do you exactly mean by broken??

**Comment by ChrisRackauckas** [comment]
It looks fine on the dev version. We just need to cut a new stable soon https://docs.sciml.ai/SciMLBenchmarksOutput/dev/Jumps/MultivariateHawkes/
